name: article
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  pretty_dio_logger: ^1.4.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  equatable: ^2.0.7
  google_fonts: ^6.2.1
  animated_list_plus: ^0.5.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lottie/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-SemiBold.ttf
